import 'server-only';
import { BRAND } from '@/lib/config';

/**
 * The channel's latest videos, from YouTube's public RSS feed.
 *
 * NO CREDENTIALS OF ANY KIND. Not an API key, not OAuth, not a token to
 * refresh, not a quota to exhaust. It is a public URL:
 *
 *   https://www.youtube.com/feeds/videos.xml?channel_id=UC…
 *
 * That is the entire reason this replaces a third-party widget. Elfsight's free
 * tier put a badge on the page and capped the widget at 200 views a month —
 * meaning it stops rendering partway through a busy month — in exchange for
 * doing something a public URL does better. Unlike the Instagram feed, whose
 * API genuinely requires a Business account and an authorisation step, there is
 * no trade-off here at all.
 *
 * CACHING is Next's data cache, not Postgres. This is public, immutable-ish
 * data that costs nothing to fetch and belongs to nobody — a database table,
 * a migration and a cron job to maintain it would be machinery in service of a
 * one-hour revalidate.
 */

export interface ChannelVideo {
  id: string;
  title: string;
  publishedAt: string;
  thumbnail: string;
  url: string;
}

const FEED_URL = `https://www.youtube.com/feeds/videos.xml?channel_id=${BRAND.youtubeChannelId}`;

/**
 * Decode the five XML entities that can appear in a title.
 *
 * Her titles contain `&` and `|` routinely ("Kundli … Hai? | Astrologer Komal
 * Kalra Podcast"), and an undecoded `&amp;` rendered on the page is the sort of
 * detail that makes a site look broken.
 */
function decode(s: string): string {
  return s
    .replace(/&lt;/g, '<')
    .replace(/&gt;/g, '>')
    .replace(/&quot;/g, '"')
    .replace(/&#39;/g, "'")
    .replace(/&apos;/g, "'")
    // Ampersand last, or `&amp;lt;` would decode twice into `<`.
    .replace(/&amp;/g, '&');
}

/**
 * Parsed with regex rather than an XML library, deliberately.
 *
 * Regex over XML is normally a mistake. It is defensible here for three
 * reasons: the document is machine-generated by one publisher in a format that
 * has been stable for over a decade, we read four flat fields and never
 * traverse structure, and — most importantly — the failure mode is safe. A
 * shape we do not recognise yields fewer entries or none, the caller renders
 * nothing, and the page is fine. It cannot corrupt anything or throw.
 *
 * If this ever needs comments, playlists or nested structure, that is the point
 * to add a real parser, not to grow the regexes.
 */
function parseFeed(xml: string): ChannelVideo[] {
  const out: ChannelVideo[] = [];

  for (const entry of xml.split('<entry>').slice(1)) {
    const id = entry.match(/<yt:videoId>([\w-]{11})<\/yt:videoId>/)?.[1];
    const title = entry.match(/<media:title>([\s\S]*?)<\/media:title>/)?.[1];
    const published = entry.match(/<published>([^<]+)<\/published>/)?.[1];
    if (!id || !title) continue;

    out.push({
      id,
      title: decode(title).trim(),
      publishedAt: published ?? '',
      // Built rather than read from <media:thumbnail>: the feed's own URL is a
      // low-resolution hqdefault, and this path is stable for every video.
      thumbnail: `https://i.ytimg.com/vi/${id}/hqdefault.jpg`,
      url: `https://www.youtube.com/watch?v=${id}`,
    });
  }

  return out;
}

/**
 * Returns [] on any failure — never throws, never returns placeholder videos.
 *
 * This renders inside the homepage. A YouTube outage, a DNS blip or a changed
 * feed format must cost one section, not the page; and an empty list makes the
 * section render nothing at all rather than showing invented content.
 */
export async function getLatestVideos(limit = 3): Promise<ChannelVideo[]> {
  try {
    const response = await fetch(FEED_URL, {
      // One hour. She posts a few times a month, so this is already far more
      // often than the content changes; the point is that a prerendered page
      // does not serve a months-old list.
      next: { revalidate: 3600 },
      signal: AbortSignal.timeout(8000),
    });

    if (!response.ok) {
      console.error(`[youtube] feed returned ${response.status}`);
      return [];
    }

    return parseFeed(await response.text()).slice(0, limit);
  } catch (error) {
    console.error('[youtube] could not read the channel feed', error);
    return [];
  }
}
