-- ============================================================================
-- 07_appointments.sql — the core booking record
-- ============================================================================

create table if not exists public.appointments (
  id            uuid primary key default gen_random_uuid(),
  -- Human-facing reference shown on receipts and quoted in support. Sequential
  -- but prefixed, e.g. KK-100248. Generated by trigger below.
  reference     text unique,

  user_id       uuid not null references public.profiles(id) on delete restrict,
  service_id    uuid not null references public.services(id) on delete restrict,

  -- Stored as an absolute instant. All slot maths happens in a single business
  -- timezone (Asia/Kolkata, see src/lib/config.ts) but is persisted as
  -- timestamptz so DST-free correctness is guaranteed and clients in other
  -- zones render correctly.
  starts_at     timestamptz not null,
  ends_at       timestamptz not null,

  status         appointment_status not null default 'pending_payment',
  payment_status payment_status     not null default 'created',

  -- Snapshot of price AT BOOKING TIME. Deliberately duplicated from services:
  -- if Komal raises her prices next month, an existing booking and its receipt
  -- must not silently change. This is the one place denormalisation is correct.
  price_paise         bigint not null check (price_paise >= 0),
  discount_paise      bigint not null default 0 check (discount_paise >= 0),
  tax_paise           bigint not null default 0 check (tax_paise >= 0),
  total_paise         bigint not null check (total_paise >= 0),
  currency            char(3) not null default 'INR',
  coupon_id           uuid,   -- FK added in 10_coupons.sql

  service_title_snapshot text not null,
  duration_minutes       integer not null,

  -- What the client wants to discuss; shown to the practitioner beforehand.
  client_question   text,
  -- Birth details captured for THIS consultation. Duplicated from profiles on
  -- purpose: a client may book on behalf of a family member, and the profile's
  -- own birth data must not be overwritten.
  subject_name      text,
  subject_birth_date  date,
  subject_birth_time  time,
  subject_birth_place text,
  subject_birth_time_known boolean not null default true,

  meeting_url   text,        -- Meet/Zoom link, filled by admin
  meeting_notes text,        -- practitioner-visible logistics

  cancelled_at     timestamptz,
  cancelled_by     uuid references public.profiles(id) on delete set null,
  cancellation_reason text,
  completed_at     timestamptz,

  rescheduled_from_id uuid references public.appointments(id) on delete set null,
  rescheduled_to_id   uuid references public.appointments(id) on delete set null,
  reschedule_requested_at timestamptz,

  hold_id       uuid references public.slot_holds(id) on delete set null,

  created_at    timestamptz not null default now(),
  updated_at    timestamptz not null default now(),

  constraint appointments_time_order check (ends_at > starts_at),
  constraint appointments_total_is_consistent
    check (total_paise = price_paise - discount_paise + tax_paise),
  constraint appointments_discount_within_price
    check (discount_paise <= price_paise)
);

-- Back-reference from holds now that appointments exists.
alter table public.slot_holds
  drop constraint if exists slot_holds_converted_appointment_fk;
alter table public.slot_holds
  add constraint slot_holds_converted_appointment_fk
  foreign key (converted_appointment_id)
  references public.appointments(id) on delete set null;

-- ---------------------------------------------------------------------------
-- THE DOUBLE-BOOKING GUARANTEE (research §5.3, layer 3)
--
-- This is the constraint that makes overlapping appointments physically
-- impossible to store — under any concurrency, from any client, including a
-- future developer writing a naive INSERT by hand.
--
-- Application-level checks cannot provide this: two concurrent transactions
-- can both read "free" before either writes. Only the database can serialise
-- it. Requires btree_gist (00_extensions.sql).
--
-- Cancelled / no-show / rescheduled-away rows are excluded from the constraint
-- so a freed slot becomes bookable again.
--
-- Violations raise SQLSTATE 23P01, which src/lib/booking/errors.ts translates
-- into "that slot was just taken" rather than a 500.
-- ---------------------------------------------------------------------------
alter table public.appointments
  drop constraint if exists appointments_no_overlap;
alter table public.appointments
  add constraint appointments_no_overlap
  exclude using gist (
    tstzrange(starts_at, ends_at, '[)') with &&
  ) where (status in ('pending_payment','confirmed','rescheduled'));

-- ---------------------------------------------------------------------------
-- Human-readable reference
-- ---------------------------------------------------------------------------
create sequence if not exists public.appointment_reference_seq start 100001;

create or replace function public.set_appointment_reference()
returns trigger
language plpgsql
as $$
begin
  if new.reference is null then
    new.reference := 'KK-' || nextval('public.appointment_reference_seq')::text;
  end if;
  return new;
end;
$$;

drop trigger if exists appointments_set_reference on public.appointments;
create trigger appointments_set_reference
  before insert on public.appointments
  for each row execute function public.set_appointment_reference();

drop trigger if exists appointments_set_updated_at on public.appointments;
create trigger appointments_set_updated_at
  before update on public.appointments
  for each row execute function public.set_updated_at();

-- ---------------------------------------------------------------------------
-- Keep profiles.appointments_count / last_appointment_at current so the admin
-- client list needs no aggregate.
-- ---------------------------------------------------------------------------
create or replace function public.sync_profile_appointment_stats()
returns trigger
language plpgsql
security definer
set search_path = public, pg_temp
as $$
declare
  target uuid := coalesce(new.user_id, old.user_id);
begin
  update public.profiles p
     set appointments_count = (
           select count(*) from public.appointments a
           where a.user_id = target
             and a.status in ('confirmed','completed')
         ),
         last_appointment_at = (
           select max(a.starts_at) from public.appointments a
           where a.user_id = target
             and a.status in ('confirmed','completed')
         )
   where p.id = target;
  return null;
end;
$$;

drop trigger if exists appointments_sync_profile_stats on public.appointments;
create trigger appointments_sync_profile_stats
  after insert or update of status or delete on public.appointments
  for each row execute function public.sync_profile_appointment_stats();

-- ---------------------------------------------------------------------------
-- RLS
-- ---------------------------------------------------------------------------
alter table public.appointments enable row level security;

drop policy if exists "appointments_select_own" on public.appointments;
create policy "appointments_select_own" on public.appointments
  for select using ((select auth.uid()) = user_id);

drop policy if exists "appointments_select_admin" on public.appointments;
create policy "appointments_select_admin" on public.appointments
  for select using (public.is_admin());

-- Clients may NOT insert appointments directly. Booking goes through
-- public.create_pending_appointment() with the service-role key, which is the
-- only path that validates the slot, the hold, and the price. If clients could
-- INSERT, they could book a ₹4,100 consultation with price_paise = 0.
--
-- Clients may update only a narrow set of fields on their own future bookings
-- (cancellation request, question text). Everything financial or scheduling
-- related is server-mediated. The WITH CHECK below pins the immutable columns.
drop policy if exists "appointments_update_own_limited" on public.appointments;
create policy "appointments_update_own_limited" on public.appointments
  for update
  using (
    (select auth.uid()) = user_id
    and status in ('pending_payment','confirmed')
  )
  with check (
    (select auth.uid()) = user_id
    and status in ('pending_payment','confirmed','cancelled')
  );

drop policy if exists "appointments_write_admin" on public.appointments;
create policy "appointments_write_admin" on public.appointments
  for all using (public.is_admin()) with check (public.is_admin());

-- ---------------------------------------------------------------------------
-- Column-level guard: even with the update policy above, a client must not be
-- able to rewrite money or times. RLS cannot express that; a trigger can.
-- ---------------------------------------------------------------------------
create or replace function public.protect_appointment_columns()
returns trigger
language plpgsql
as $$
begin
  if public.is_service_role() or public.is_admin() then
    return new;
  end if;

  if new.price_paise    is distinct from old.price_paise
  or new.total_paise    is distinct from old.total_paise
  or new.discount_paise is distinct from old.discount_paise
  or new.tax_paise      is distinct from old.tax_paise
  or new.payment_status is distinct from old.payment_status
  or new.starts_at      is distinct from old.starts_at
  or new.ends_at        is distinct from old.ends_at
  or new.service_id     is distinct from old.service_id
  or new.user_id        is distinct from old.user_id
  then
    raise exception 'This field cannot be modified directly'
      using errcode = '42501';
  end if;

  -- The only status change a client may make is cancelling.
  if new.status is distinct from old.status and new.status <> 'cancelled' then
    raise exception 'Status changes other than cancellation are not permitted'
      using errcode = '42501';
  end if;

  return new;
end;
$$;

drop trigger if exists appointments_protect_columns on public.appointments;
create trigger appointments_protect_columns
  before update on public.appointments
  for each row execute function public.protect_appointment_columns();
